redirect_no_errors

diff --git a/0x0C-web_server/3-redirection b/0x0C-web_server/3-redirection
--- a/0x0C-web_server/3-redirection
+++ b/0x0C-web_server/3-redirection
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
-# Add a custom redirection page
-set -e  # Exit immediately if a command exits with a non-zero status
+# Exit immediately if a command exits with a non-zero status
+set -e
 
 # Install Nginx server
 if ! sudo apt-get update; then
@@ -31,8 +31,14 @@ if ! sudo service nginx restart; then
     exit 1
 fi
 
+# Define Nginx configuration file path
+NGINX_CONFIG_FILE="/etc/nginx/sites-available/default"
+
+# Remove existing redirection if it exists
+sudo sed -i '/location \/redirect_me { return 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4; }/d' $NGINX_CONFIG_FILE
+
 # Update Nginx configuration file to add redirection
-if ! sudo sed -i '/server_name _;/a \\n    location /redirect_me { return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4; }' /etc/nginx/sites-available/default; then
+if ! sudo sed -i '/server_name _;/a \\n    location /redirect_me { return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4; }' $NGINX_CONFIG_FILE; then
     echo "Failed to update Nginx configuration"
     exit 1
 fi
